[profile.default]
src = "contracts"
out = "artifacts"
libs = ["lib"]
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
arbitrum_goerli = "${ARBITRUM_GOERLI_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"
bsc_testnet = "${BSC_TESTNET_RPC_URL}"

[etherscan]
arbitrum_goerli = { key = "${ARBISCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }
bsc_testnet = { key = "${BSCSCAN_API_KEY}" }



# See more config options https://github.com/foundry-rs/foundry/tree/master/config
